### ISSUE TITLE
This plugin cannot be installed in the scrypted management console

### ISSUE THREAD

**Issue by brandonb927** [FiachAntaw/scrypted-sensibo#1]
As the title states, I'm having an issue attempting to install this plugin in the scrypted management console.

The steps to repro are here https://github.com/koush/scrypted/issues/1419

I was informed in the `scrypted` repo that this is not a scrypted issue... so I'm posting here instead.

**Comment by koush** [comment]
patched this to maybe fix it, but the maintainer should take a look.

**Comment by FiachAntaw** [comment]
I've merged @koush's fixes and also fixed another issue (I was incorrectly publishing the Refresh interface in package.json), but it looks like the main cause may have been the lack of a .npmignore file - the .gitignore was being used as a fallback, and as it includes the `dist/` folder this meant that the webpack zip with the built plugin was being stripped out during the publishing process. I'm not sure if this has always been the case (apologies if so) but it should hopefully work now; please let me know if it doesn't or if you hit on any other snags. Happy to see the plugin get some use!

**Comment by brandonb927** [comment]
I am able to install the plugin now! Thank you for the quick turnaround, I appreciate it immensely. I'm in the process of migrating off Homebridge and this was the last thing I had to migrate over. 🍻
