### ISSUE TITLE
Sensibo has implemented rate limiting

### ISSUE THREAD

**Issue by pvanamst** [FiachAntaw/scrypted-sensibo#3]
Sensibo appears to have implemented rate limiting. I am seeing the following errors in the logs:

linux arm64 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29)
server version: 0.111.0
plugin version: @scrypted/sensibo 0.0.4
full
########################
6/6/2024, 10:09:44 AM
########################
starting plugin @scrypted/sensibo
node modules /server/volume/plugins/@scrypted/sensibo/node20-linux-arm64-20240321
plugin loaded
Error whilst reading pod state (HTTP Status: 429, API Status: 429, Reason: undefined, Message: API Limit exceeded. Use "Accept-Encoding: gzip" to increase the rate limit.)
Error whilst writing pod AcState (HTTP Status: 429, API Status: 429, Reason: undefined, Message: API Limit exceeded. Use "Accept-Encoding: gzip" to increase the rate limit.)

Is there any possibility of implementing "Accept-Encoding: gzip" to increase the rate limit?

**Comment by FiachAntaw** [comment]
Hi, thanks for the report! I’ll work on this in the next day or two, should be a quick fix.

**Comment by pvanamst** [comment]
Much appreciated. Thank you.

**Comment by FiachAntaw** [comment]
I've updated to a new version of Axios which supports gzip encoding by default, and it should now be sending the correct header. I wasn't able to trigger the rate limit myself; are you able to confirm that this fixes your issue?

**Comment by pvanamst** [comment]
Fiach,As far as I can see version 0.0.5 appears to work. Thank you for all of your help. I'll continue to test. PaulSent from my iPhoneOn Jun 8, 2024, at 18:42, Fiach Antaw ***@***.***> wrote:﻿
I've updated to a new version of Axios which supports gzip encoding by default, and it should now be sending the correct header. I wasn't able to trigger the rate limit myself; are you able to confirm that this fixes your issue?
